# Read https://github.com/crystal-lang/crystal-sqlite3/blob/master/README.md for sqlite options
db_path: "sqlite3://./bbs.db"
secret_key: "ChangeMe"

# Sysop credentials
sysop_name: ""
sysop_pass: ""

# Board settings
name: "piezo"
description: "chat about stuff"
max_threads: 50
max_replies: 500
threads_per_page: 10